apiVersion: v1
kind: Service
metadata:
  name: ecotiendas-backend
  labels:
    service: ecotiendas-backend
spec:
  ports:
  - name: "5000"
    port: 5000
    targetPort: 5000
  selector:
    service: ecotiendas-backend