apiVersion: apps/v1
kind: Deployment
metadata:
  name: ecotiendas-backend
  namespace: piloto
  labels:
    service: ecotiendas-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      service: ecotiendas-backend
  template:
    metadata:
      labels:
        service: ecotiendas-backend
    spec:
      restartPolicy: Always
      containers:
        - name: ecotiendas-backend
          image: backend_app
          imagePullPolicy: Always 
          ports:
          - containerPort: 5000    
        - name: cloud-sql-proxy
          image: gcr.io/cloudsql-docker/gce-proxy:1.17
          command:
            - "/cloud_sql_proxy"
            - "-instances=ecotiendas-327016:us-central1:root=tcp:5432"
            - "-credential_file=/secrets/key.json"
          securityContext:
            runAsNonRoot: true
          volumeMounts:
          - name: cloudsql-instance-credentials
            mountPath: /secrets/
            readOnly: true
          resources:
            requests:
              memory: "0.5Gi"
              cpu:    "100m"
      volumes:
      - name: cloudsql-instance-credentials
        secret:
          secretName: cloudsql-instance-credentials
          
      
      
      