apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- deployment/launch/backend-deployment.yaml
- deployment/launch/backend-service.yaml
- deployment/launch/frontend-deployment.yaml
- deployment/launch/frontend-service.yaml
- deployment/launch/reverse-proxy-deployment.yaml
- deployment/launch/reverse-proxy-service.yaml
