"""empty message

Revision ID: 0804bf672aba
Revises: bea225643347
Create Date: 2021-11-15 17:36:49.414529

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0804bf672aba'
down_revision = 'bea225643347'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('codigos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('token', sa.String(), nullable=True),
    sa.Column('canjeado', sa.Boolean(), nullable=False),
    sa.Column('ecoamigo_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['ecoamigo_id'], ['ecoAmigos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('canjes', sa.Column('cantidad_total', sa.Integer(), nullable=True))
    op.alter_column('canjes', 'ecoamigo_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('canjes', 'ecoadmin_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.add_column('detalle_canje', sa.Column('cantidad', sa.Integer(), nullable=True))
    op.add_column('detalle_canje', sa.Column('codigo_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'detalle_canje', 'codigos', ['codigo_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'detalle_canje', type_='foreignkey')
    op.drop_column('detalle_canje', 'codigo_id')
    op.drop_column('detalle_canje', 'cantidad')
    op.alter_column('canjes', 'ecoadmin_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('canjes', 'ecoamigo_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_column('canjes', 'cantidad_total')
    op.drop_table('codigos')
    # ### end Alembic commands ###
