"""empty message

Revision ID: 08aa92cda052
Revises: 241df9c7cef7
Create Date: 2021-06-25 11:02:45.898354

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '08aa92cda052'
down_revision = '241df9c7cef7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ecoAmigos', sa.Column('fecha_nacimiento', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ecoAmigos', 'fecha_nacimiento')
    # ### end Alembic commands ###
