"""empty message

Revision ID: 0dac35f0196c
Revises: ef28f5c1b4fa
Create Date: 2021-06-28 09:50:28.483545

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0dac35f0196c'
down_revision = 'ef28f5c1b4fa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('detalle_ticket',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ticket_id', sa.Integer(), nullable=False),
    sa.Column('material_id', sa.Integer(), nullable=False),
    sa.Column('cantidad_kg', sa.Integer(), nullable=False),
    sa.Column('ecopuntos', sa.Integer(), nullable=False),
    sa.Column('cantidad_m3', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['material_id'], ['materiales.id'], ),
    sa.ForeignKeyConstraint(['ticket_id'], ['tickets.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('detalle_ticket', 'id')
    # ### end Alembic commands ###
