"""empty message

Revision ID: 1e726825e3f8
Revises: 224850c160c9
Create Date: 2021-06-25 09:32:03.078051

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '1e726825e3f8'
down_revision = '224850c160c9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('materiales', sa.Column('cantidad_m3', sa.Integer(), nullable=True))
    op.alter_column('tickets', 'fecha',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('tickets', 'fecha',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.drop_column('materiales', 'cantidad_m3')
    # ### end Alembic commands ###
