"""empty message

Revision ID: 1ff351ead5a7
Revises: 2cfe69ab199f
Create Date: 2021-12-22 09:06:56.179805

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1ff351ead5a7'
down_revision = '2cfe69ab199f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ecoTiendas', sa.Column('is_movil', sa.Boolean(), nullable=True))
    op.alter_column('productos', 'stock_sin_despachar',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('productos', 'stock_real',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('productos', 'stock_real',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('productos', 'stock_sin_despachar',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_column('ecoTiendas', 'is_movil')
    # ### end Alembic commands ###
