"""empty message

Revision ID: 224850c160c9
Revises: 60cd7087d210
Create Date: 2021-06-24 15:15:40.200596

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '224850c160c9'
down_revision = '60cd7087d210'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ecoTiendas', sa.Column('cantidad_actual_m3', sa.Integer(), nullable=False))
    op.drop_column('ecoTiendas', 'cantidad_acutal_m3')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ecoTiendas', sa.Column('cantidad_acutal_m3', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_column('ecoTiendas', 'cantidad_actual_m3')
    # ### end Alembic commands ###
