"""empty message

Revision ID: 28a23d51af10
Revises: 51f79ddbb3a2
Create Date: 2021-07-06 20:25:42.808201

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '28a23d51af10'
down_revision = '51f79ddbb3a2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('tickets', 'total_ecopuntos',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('tickets', 'total_ecopuntos',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
