"""empty message

Revision ID: 2cfe69ab199f
Revises: 9a66ca6fd3d6
Create Date: 2021-11-18 10:24:04.021906

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2cfe69ab199f'
down_revision = '9a66ca6fd3d6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('productos', sa.Column('stock_sin_despachar', sa.Integer(), nullable=True))
    op.add_column('productos', sa.Column('stock_real', sa.Integer(), nullable=True))
    op.drop_column('productos', 'stock')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('productos', sa.Column('stock', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_column('productos', 'stock_real')
    op.drop_column('productos', 'stock_sin_despachar')
    # ### end Alembic commands ###
