"""empty message

Revision ID: 2e26796dbaa8
Revises: 28a23d51af10
Create Date: 2021-07-07 16:00:21.716734

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2e26796dbaa8'
down_revision = '28a23d51af10'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('regionales',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cedula', sa.String(), nullable=False),
    sa.Column('fecha_nacimiento', sa.String(), nullable=True),
    sa.Column('nombre', sa.String(), nullable=True),
    sa.Column('fecha_registro', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('apellido', sa.String(), nullable=True),
    sa.Column('direccion', sa.String(), nullable=True),
    sa.Column('genero', sa.String(), nullable=False),
    sa.Column('correo', sa.String(), nullable=False),
    sa.Column('telefono', sa.String(), nullable=True),
    sa.Column('sector_id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['sector_id'], ['sectores.id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('ecoAdmins', sa.Column('regional_id', sa.Integer()))
    op.create_foreign_key(None, 'ecoAdmins', 'regionales', ['regional_id'], ['id'])
    op.add_column('ecoTiendas', sa.Column('regional_id', sa.Integer()))
    op.create_foreign_key(None, 'ecoTiendas', 'regionales', ['regional_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'ecoTiendas', type_='foreignkey')
    op.drop_column('ecoTiendas', 'regional_id')
    op.drop_constraint(None, 'ecoAdmins', type_='foreignkey')
    op.drop_column('ecoAdmins', 'regional_id')
    op.drop_table('regionales')
    # ### end Alembic commands ###
