"""empty message

Revision ID: 3820c4b0cad9
Revises: 862f4321fc52
Create Date: 2021-07-06 20:10:04.044735

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3820c4b0cad9'
down_revision = '862f4321fc52'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('tickets', 'ecoamigo_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('tickets', 'ecoamigo_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
