"""empty message

Revision ID: 51f79ddbb3a2
Revises: 3820c4b0cad9
Create Date: 2021-07-06 20:16:44.298229

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '51f79ddbb3a2'
down_revision = '3820c4b0cad9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('detalle_ticket', 'ecopuntos',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('detalle_ticket', 'ecopuntos',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
