"""empty message

Revision ID: 5b1df9083854
Revises: 
Create Date: 2021-07-29 17:27:30.356563

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5b1df9083854'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sectores',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(), nullable=True),
    sa.Column('zipCode', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tipoMateriales',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(), nullable=False),
    sa.Column('detalle', sa.String(), nullable=False),
    sa.Column('codigo', sa.String(), nullable=False),
    sa.Column('ecopuntos', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tipoProductos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(), nullable=False),
    sa.Column('detalle', sa.String(), nullable=False),
    sa.Column('codigo', sa.String(), nullable=False),
    sa.Column('ecopuntos', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('usuarios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('usuario', sa.String(), nullable=False),
    sa.Column('contraseña', sa.String(), nullable=False),
    sa.Column('tipo', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ecoAmigos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cedula', sa.String(), nullable=False),
    sa.Column('fecha_nacimiento', sa.String(), nullable=True),
    sa.Column('nombre', sa.String(), nullable=True),
    sa.Column('fecha_registro', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('apellido', sa.String(), nullable=True),
    sa.Column('direccion', sa.String(), nullable=True),
    sa.Column('foto', sa.LargeBinary(), nullable=True),
    sa.Column('genero', sa.String(), nullable=False),
    sa.Column('correo', sa.String(), nullable=False),
    sa.Column('telefono', sa.String(), nullable=True),
    sa.Column('ecopuntos', sa.Float(), nullable=True),
    sa.Column('sector_id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['sector_id'], ['sectores.id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('materiales',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(), nullable=False),
    sa.Column('detalle', sa.String(), nullable=True),
    sa.Column('codigo', sa.String(), nullable=True),
    sa.Column('foto', sa.LargeBinary(), nullable=True),
    sa.Column('ecopuntos', sa.Float(), nullable=False),
    sa.Column('cantidad_m3', sa.Float(), nullable=False),
    sa.Column('valor_max', sa.Float(), nullable=True),
    sa.Column('valor_min', sa.Float(), nullable=True),
    sa.Column('tipo_material_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['tipo_material_id'], ['tipoMateriales.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('productos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(), nullable=False),
    sa.Column('detalle', sa.String(), nullable=True),
    sa.Column('codigo', sa.String(), nullable=True),
    sa.Column('foto', sa.LargeBinary(), nullable=False),
    sa.Column('stock', sa.Integer(), nullable=False),
    sa.Column('ecopuntos', sa.Float(), nullable=False),
    sa.Column('valor_max', sa.Float(), nullable=True),
    sa.Column('valor_min', sa.Float(), nullable=True),
    sa.Column('tipo_producto_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['tipo_producto_id'], ['tipoProductos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('zonales',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cedula', sa.String(), nullable=False),
    sa.Column('fecha_nacimiento', sa.String(), nullable=True),
    sa.Column('nombre', sa.String(), nullable=True),
    sa.Column('fecha_registro', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('apellido', sa.String(), nullable=True),
    sa.Column('direccion', sa.String(), nullable=True),
    sa.Column('foto', sa.LargeBinary(), nullable=True),
    sa.Column('genero', sa.String(), nullable=False),
    sa.Column('correo', sa.String(), nullable=False),
    sa.Column('telefono', sa.String(), nullable=True),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('bodegueros',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cedula', sa.String(), nullable=False),
    sa.Column('fecha_nacimiento', sa.String(), nullable=True),
    sa.Column('nombre', sa.String(), nullable=True),
    sa.Column('fecha_registro', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('apellido', sa.String(), nullable=True),
    sa.Column('direccion', sa.String(), nullable=True),
    sa.Column('foto', sa.LargeBinary(), nullable=True),
    sa.Column('genero', sa.String(), nullable=False),
    sa.Column('correo', sa.String(), nullable=False),
    sa.Column('telefono', sa.String(), nullable=True),
    sa.Column('zonal_id', sa.Integer(), nullable=True),
    sa.Column('sector_id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['sector_id'], ['sectores.id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.ForeignKeyConstraint(['zonal_id'], ['zonales.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ecoAdmins',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cedula', sa.String(), nullable=False),
    sa.Column('fecha_nacimiento', sa.String(), nullable=True),
    sa.Column('nombre', sa.String(), nullable=True),
    sa.Column('apellido', sa.String(), nullable=True),
    sa.Column('direccion', sa.String(), nullable=True),
    sa.Column('foto', sa.LargeBinary(), nullable=True),
    sa.Column('fecha_registro', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('genero', sa.String(), nullable=False),
    sa.Column('correo', sa.String(), nullable=False),
    sa.Column('telefono', sa.String(), nullable=True),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('zonal_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.ForeignKeyConstraint(['zonal_id'], ['zonales.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('canjes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('numero_semana', sa.String(), nullable=False),
    sa.Column('mes', sa.String(), nullable=False),
    sa.Column('año', sa.String(), nullable=False),
    sa.Column('nombre_cliente', sa.String(), nullable=True),
    sa.Column('total_ecopuntos', sa.Float(), nullable=True),
    sa.Column('ecoamigo_id', sa.Integer(), nullable=True),
    sa.Column('ecoadmin_id', sa.Integer(), nullable=False),
    sa.Column('fecha_registro', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['ecoadmin_id'], ['ecoAdmins.id'], ),
    sa.ForeignKeyConstraint(['ecoamigo_id'], ['ecoAmigos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ecoTiendas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('latitud', sa.String(), nullable=False),
    sa.Column('longitud', sa.String(), nullable=False),
    sa.Column('fecha_registro', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('capacidad_maxima_m3', sa.Float(), nullable=False),
    sa.Column('capacidad_maxima_kg', sa.Float(), nullable=False),
    sa.Column('cantidad_actual_m3', sa.Float(), nullable=False),
    sa.Column('cantidad_actual_kg', sa.Float(), nullable=False),
    sa.Column('provincia', sa.String(), nullable=True),
    sa.Column('ciudad', sa.String(), nullable=True),
    sa.Column('fecha_apertura', sa.String(), nullable=True),
    sa.Column('nombre', sa.String(), nullable=True),
    sa.Column('meta_semanal', sa.Integer(), nullable=True),
    sa.Column('zonal_id', sa.Integer(), nullable=True),
    sa.Column('ecoadmin_id', sa.Integer(), nullable=True),
    sa.Column('sectores_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['ecoadmin_id'], ['ecoAdmins.id'], ),
    sa.ForeignKeyConstraint(['sectores_id'], ['sectores.id'], ),
    sa.ForeignKeyConstraint(['zonal_id'], ['zonales.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('almacenes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cantidad_kg', sa.Float(), nullable=True),
    sa.Column('cantidad_m3', sa.Float(), nullable=True),
    sa.Column('cantidad_actual_kg', sa.Float(), nullable=True),
    sa.Column('cantidad_actual_m3', sa.Float(), nullable=True),
    sa.Column('ecotienda_id', sa.Integer(), nullable=False),
    sa.Column('material_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['ecotienda_id'], ['ecoTiendas.id'], ),
    sa.ForeignKeyConstraint(['material_id'], ['materiales.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('detalle_canje',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('canje_id', sa.Integer(), nullable=True),
    sa.Column('producto_id', sa.Integer(), nullable=True),
    sa.Column('numero_semana', sa.String(), nullable=False),
    sa.Column('mes', sa.String(), nullable=False),
    sa.Column('año', sa.String(), nullable=False),
    sa.Column('ecopuntos', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['canje_id'], ['canjes.id'], ),
    sa.ForeignKeyConstraint(['producto_id'], ['productos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('records',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ecotienda_id', sa.Integer(), nullable=False),
    sa.Column('peso', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['ecotienda_id'], ['ecoTiendas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tickets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('numero_semana', sa.String(), nullable=False),
    sa.Column('mes', sa.String(), nullable=False),
    sa.Column('año', sa.String(), nullable=False),
    sa.Column('cliente', sa.String(), nullable=True),
    sa.Column('entrada', sa.Boolean(), nullable=False),
    sa.Column('total_kg', sa.Float(), nullable=False),
    sa.Column('total_m3', sa.Float(), nullable=False),
    sa.Column('total_ecopuntos', sa.Float(), nullable=True),
    sa.Column('ecoamigo_id', sa.Integer(), nullable=True),
    sa.Column('ecotienda_id', sa.Integer(), nullable=False),
    sa.Column('zonal_id', sa.Integer(), nullable=False),
    sa.Column('fecha_registro', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['ecoamigo_id'], ['ecoAmigos.id'], ),
    sa.ForeignKeyConstraint(['ecotienda_id'], ['ecoTiendas.id'], ),
    sa.ForeignKeyConstraint(['zonal_id'], ['zonales.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('detalle_ticket',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ticket_id', sa.Integer(), nullable=True),
    sa.Column('material_id', sa.Integer(), nullable=True),
    sa.Column('numero_semana', sa.String(), nullable=False),
    sa.Column('mes', sa.String(), nullable=False),
    sa.Column('año', sa.String(), nullable=False),
    sa.Column('cantidad_kg', sa.Float(), nullable=False),
    sa.Column('ecopuntos', sa.Float(), nullable=True),
    sa.Column('entrada', sa.Boolean(), nullable=True),
    sa.Column('cantidad_m3', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['material_id'], ['materiales.id'], ),
    sa.ForeignKeyConstraint(['ticket_id'], ['tickets.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('detalle_ticket')
    op.drop_table('tickets')
    op.drop_table('records')
    op.drop_table('detalle_canje')
    op.drop_table('almacenes')
    op.drop_table('ecoTiendas')
    op.drop_table('canjes')
    op.drop_table('ecoAdmins')
    op.drop_table('bodegueros')
    op.drop_table('zonales')
    op.drop_table('productos')
    op.drop_table('materiales')
    op.drop_table('ecoAmigos')
    op.drop_table('usuarios')
    op.drop_table('tipoProductos')
    op.drop_table('tipoMateriales')
    op.drop_table('sectores')
    # ### end Alembic commands ###
