"""empty message

Revision ID: 60cd7087d210
Revises: 
Create Date: 2021-06-24 11:27:04.605309

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '60cd7087d210'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sectores',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(), nullable=True),
    sa.Column('zipCode', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tipoMateriales',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(), nullable=False),
    sa.Column('detalle', sa.String(), nullable=False),
    sa.Column('codigo', sa.String(), nullable=False),
    sa.Column('ecopuntos', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('usuarios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('usuario', sa.String(), nullable=False),
    sa.Column('contraseña', sa.String(), nullable=False),
    sa.Column('tipo', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ecoAdmins',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cedula', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(), nullable=True),
    sa.Column('apellido', sa.String(), nullable=True),
    sa.Column('direccion', sa.String(), nullable=True),
    sa.Column('genero', sa.String(), nullable=False),
    sa.Column('correo', sa.String(), nullable=False),
    sa.Column('telefono', sa.Integer(), nullable=True),
    sa.Column('sector_id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['sector_id'], ['sectores.id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ecoAmigos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cedula', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(), nullable=True),
    sa.Column('apellido', sa.String(), nullable=True),
    sa.Column('direccion', sa.String(), nullable=True),
    sa.Column('genero', sa.String(), nullable=False),
    sa.Column('correo', sa.String(), nullable=False),
    sa.Column('telefono', sa.String(), nullable=True),
    sa.Column('ecopuntos', sa.Integer(), nullable=True),
    sa.Column('sector_id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['sector_id'], ['sectores.id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('materiales',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(), nullable=False),
    sa.Column('detalle', sa.String(), nullable=False),
    sa.Column('codigo', sa.String(), nullable=False),
    sa.Column('ecopuntos', sa.Integer(), nullable=False),
    sa.Column('valor_max', sa.Integer(), nullable=False),
    sa.Column('valor_min', sa.Integer(), nullable=False),
    sa.Column('tipo_material_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['tipo_material_id'], ['tipoMateriales.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ecoTiendas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('latitud', sa.String(), nullable=False),
    sa.Column('longitud', sa.String(), nullable=False),
    sa.Column('capacidad_maxima_m3', sa.Integer(), nullable=False),
    sa.Column('capacidad_maxima_kg', sa.Integer(), nullable=False),
    sa.Column('cantidad_acutal_m3', sa.Integer(), nullable=False),
    sa.Column('cantidad_actual_kg', sa.Integer(), nullable=False),
    sa.Column('ecoadmin_id', sa.Integer(), nullable=False),
    sa.Column('sectores_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['ecoadmin_id'], ['ecoAdmins.id'], ),
    sa.ForeignKeyConstraint(['sectores_id'], ['sectores.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('almacenes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cantidad_kg', sa.Integer(), nullable=True),
    sa.Column('cantidad_m3', sa.Integer(), nullable=True),
    sa.Column('ecotienda_id', sa.Integer(), nullable=False),
    sa.Column('material_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['ecotienda_id'], ['ecoTiendas.id'], ),
    sa.ForeignKeyConstraint(['material_id'], ['materiales.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tickets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fecha', sa.DateTime(), nullable=False),
    sa.Column('numero_semana', sa.String(), nullable=False),
    sa.Column('entrada', sa.Boolean(), nullable=False),
    sa.Column('total_kg', sa.Integer(), nullable=False),
    sa.Column('total_m3', sa.Integer(), nullable=False),
    sa.Column('total_ecopuntos', sa.Integer(), nullable=False),
    sa.Column('ecoamigo_id', sa.Integer(), nullable=False),
    sa.Column('ecotienda_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['ecoamigo_id'], ['ecoAmigos.id'], ),
    sa.ForeignKeyConstraint(['ecotienda_id'], ['ecoTiendas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('detalle_ticket',
    sa.Column('ticket_id', sa.Integer(), nullable=False),
    sa.Column('material_id', sa.Integer(), nullable=False),
    sa.Column('cantidad_kg', sa.Integer(), nullable=False),
    sa.Column('ecopuntos', sa.Integer(), nullable=False),
    sa.Column('cantidad_m3', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['material_id'], ['materiales.id'], ),
    sa.ForeignKeyConstraint(['ticket_id'], ['tickets.id'], ),
    sa.PrimaryKeyConstraint('ticket_id', 'material_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('detalle_ticket')
    op.drop_table('tickets')
    op.drop_table('almacenes')
    op.drop_table('ecoTiendas')
    op.drop_table('materiales')
    op.drop_table('ecoAmigos')
    op.drop_table('ecoAdmins')
    op.drop_table('usuarios')
    op.drop_table('tipoMateriales')
    op.drop_table('sectores')
    # ### end Alembic commands ###
