"""empty message

Revision ID: 6182e4a3e261
Revises: 0dac35f0196c
Create Date: 2021-06-28 11:15:27.095663

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6182e4a3e261'
down_revision = '0dac35f0196c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('detalle_ticket', 'ticket_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('detalle_ticket', 'material_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.add_column('tickets', sa.Column('cliente', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tickets', 'cliente')
    op.alter_column('detalle_ticket', 'material_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('detalle_ticket', 'ticket_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
