"""empty message

Revision ID: 70c01d77323a
Revises: e2a6a61cbe1a
Create Date: 2021-11-17 10:29:41.877837

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '70c01d77323a'
down_revision = 'e2a6a61cbe1a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('ecoTiendas', 'latitud',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('ecoTiendas', 'longitud',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('ecoTiendas', 'longitud',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('ecoTiendas', 'latitud',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###
