"""empty message

Revision ID: 75d04284bcb9
Revises: 4d4e912418c7
Create Date: 2021-12-28 11:59:28.890650

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '75d04284bcb9'
down_revision = '4d4e912418c7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pedidos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('completado', sa.Boolean(), nullable=True),
    sa.Column('ecoamigo_id', sa.Integer(), nullable=False),
    sa.Column('ecopicker_id', sa.Integer(), nullable=False),
    sa.Column('latitud', sa.String(), nullable=True),
    sa.Column('longitud', sa.String(), nullable=True),
    sa.Column('fecha_registro', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('numero_semana', sa.String(), nullable=False),
    sa.Column('mes', sa.String(), nullable=False),
    sa.Column('año', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['ecoamigo_id'], ['ecoAmigos.id'], ),
    sa.ForeignKeyConstraint(['ecopicker_id'], ['ecoAmigos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('tickets', sa.Column('transito', sa.Boolean(), nullable=True))
    op.add_column('tickets', sa.Column('completado', sa.Boolean(), nullable=True))
    op.add_column('tickets', sa.Column('ecopicker_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'tickets', 'ecopicker', ['ecopicker_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'tickets', type_='foreignkey')
    op.drop_column('tickets', 'ecopicker_id')
    op.drop_column('tickets', 'completado')
    op.drop_column('tickets', 'transito')
    op.drop_table('pedidos')
    # ### end Alembic commands ###
