"""empty message

Revision ID: 7f30b955308b
Revises: ec4bb506c63a
Create Date: 2021-07-07 17:23:37.428309

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7f30b955308b'
down_revision = 'ec4bb506c63a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('detalle_ticket', 'numero_semana',
               existing_type=sa.VARCHAR())
    op.alter_column('detalle_ticket', 'mes',
               existing_type=sa.VARCHAR())
    op.alter_column('detalle_ticket', 'año',
               existing_type=sa.VARCHAR())
    op.drop_constraint('regionales_sector_id_fkey', 'regionales', type_='foreignkey')
    op.drop_column('regionales', 'sector_id')
    op.alter_column('tickets', 'mes',
               existing_type=sa.VARCHAR())
    op.alter_column('tickets', 'año',
               existing_type=sa.VARCHAR())
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('tickets', 'año',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('tickets', 'mes',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.add_column('regionales', sa.Column('sector_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key('regionales_sector_id_fkey', 'regionales', 'sectores', ['sector_id'], ['id'])
    op.alter_column('detalle_ticket', 'año',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('detalle_ticket', 'mes',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('detalle_ticket', 'numero_semana',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###
