"""empty message

Revision ID: 862f4321fc52
Revises: f07f9792fafd
Create Date: 2021-07-06 19:32:58.579634

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '862f4321fc52'
down_revision = 'f07f9792fafd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ecoTiendas', sa.Column('meta_semanal', sa.Integer(), nullable=True))
    op.drop_column('ecoTiendas', 'meta_general')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ecoTiendas', sa.Column('meta_general', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('ecoTiendas', 'meta_semanal')
    # ### end Alembic commands ###
