"""empty message

Revision ID: 9a66ca6fd3d6
Revises: 70c01d77323a
Create Date: 2021-11-18 09:20:28.277118

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9a66ca6fd3d6'
down_revision = '70c01d77323a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('problemas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ecoamigo_id', sa.Integer(), nullable=False),
    sa.Column('problema', sa.String(), nullable=True),
    sa.Column('fecha_registro', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('numero_semana', sa.String(), nullable=False),
    sa.Column('mes', sa.String(), nullable=False),
    sa.Column('año', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['ecoamigo_id'], ['ecoAmigos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('problemas')
    # ### end Alembic commands ###
