"""empty message

Revision ID: aa44b376fda0
Revises: 1fed9eba8529
Create Date: 2021-07-06 18:36:16.025237

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'aa44b376fda0'
down_revision = '1fed9eba8529'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ecoTiendas', sa.Column('meta_semanal', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ecoTiendas', 'meta_semanal')
    # ### end Alembic commands ###
