"""empty message

Revision ID: bea225643347
Revises: 55393677169e
Create Date: 2021-11-08 11:08:01.583326

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bea225643347'
down_revision = '55393677169e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ecoAmigos', sa.Column('foto', sa.LargeBinary(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ecoAmigos', 'foto')
    # ### end Alembic commands ###
