"""empty message

Revision ID: ea564a1a362d
Revises: bc992ba750a4
Create Date: 2021-06-29 13:53:04.081519

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'ea564a1a362d'
down_revision = 'bc992ba750a4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tickets', sa.Column('fecha_registro', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    op.drop_column('tickets', 'fecha')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tickets', sa.Column('fecha', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.drop_column('tickets', 'fecha_registro')
    # ### end Alembic commands ###
