"""empty message

Revision ID: ec4bb506c63a
Revises: 13b0db37592d
Create Date: 2021-07-07 16:48:02.398287

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ec4bb506c63a'
down_revision = '13b0db37592d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('detalle_ticket', 'numero_semana',
               existing_type=sa.VARCHAR(),
               )
    op.alter_column('detalle_ticket', 'mes',
               existing_type=sa.VARCHAR(),
               )
    op.alter_column('detalle_ticket', 'año',
               existing_type=sa.VARCHAR(),
               )
    op.alter_column('tickets', 'mes',
               existing_type=sa.VARCHAR(),
               )
    op.alter_column('tickets', 'año',
               existing_type=sa.VARCHAR(),
               )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('tickets', 'año',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('tickets', 'mes',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('detalle_ticket', 'año',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('detalle_ticket', 'mes',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('detalle_ticket', 'numero_semana',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###
