"""empty message

Revision ID: ef28f5c1b4fa
Revises: fbc714d3e4a4
Create Date: 2021-06-28 08:00:51.327689

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ef28f5c1b4fa'
down_revision = 'fbc714d3e4a4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('detalle_ticket', 'cantidad_total')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('detalle_ticket', sa.Column('cantidad_total', sa.INTEGER(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
