"""empty message

Revision ID: f07f9792fafd
Revises: aa44b376fda0
Create Date: 2021-07-06 19:19:23.815868

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f07f9792fafd'
down_revision = 'aa44b376fda0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('almacenes', sa.Column('cantidad_actual_kg', sa.Integer(), nullable=True))
    op.add_column('almacenes', sa.Column('cantidad_actual_m3', sa.Integer(), nullable=True))
    op.add_column('ecoTiendas', sa.Column('meta_general', sa.Integer(), nullable=True))
    op.drop_column('ecoTiendas', 'meta_semanal')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ecoTiendas', sa.Column('meta_semanal', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('ecoTiendas', 'meta_general')
    op.drop_column('almacenes', 'cantidad_actual_m3')
    op.drop_column('almacenes', 'cantidad_actual_kg')
    # ### end Alembic commands ###
