"""empty message

Revision ID: fbc714d3e4a4
Revises: 08aa92cda052
Create Date: 2021-06-28 07:59:59.871756

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fbc714d3e4a4'
down_revision = '08aa92cda052'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('detalle_ticket', sa.Column('cantidad_total', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('detalle_ticket', 'cantidad_total')
    # ### end Alembic commands ###
